#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-kramdown
Version  : 1.7.0
Release  : 7
URL      : https://rubygems.org/downloads/kramdown-1.7.0.gem
Source0  : https://rubygems.org/downloads/kramdown-1.7.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-kramdown-bin
BuildRequires : ruby
BuildRequires : rubygem-coderay
BuildRequires : rubygem-minitest
BuildRequires : rubygem-pdf-core
BuildRequires : rubygem-prawn
BuildRequires : rubygem-prawn-table
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-stringex
BuildRequires : rubygem-ttfunk

%description
# kramdown
## Readme first!
kramdown was originally licensed under the GPL until the 1.0.0 release. However, due to the many
requests it is now released under the MIT license and therefore can easily be used in commercial
projects, too.

%package bin
Summary: bin components for the rubygem-kramdown package.
Group: Binaries

%description bin
bin components for the rubygem-kramdown package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n kramdown-1.7.0
gem spec %{SOURCE0} -l --ruby > rubygem-kramdown.gemspec

%build
gem build rubygem-kramdown.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
kramdown-1.7.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/kramdown-1.7.0
ruby -v -I.:lib:test test*/test_*.rb || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/kramdown-1.7.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/AUTHORS
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/CONTRIBUTERS
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/benchmark.sh
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/generate_data.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/mdbasics.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/mdsyntax.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/testing.sh
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/benchmark/timing.sh
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/bin/kramdown
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/data/kramdown/document.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/data/kramdown/document.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/_design.scss
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/bg.png
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/default.scss
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/default.template
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/documentation.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/documentation.template
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/index.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/installation.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/links.markdown
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/metainfo
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/news.feed
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/news.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/options.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/quickref.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/sidebar.template
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/sitemap.sitemap
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/syntax.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/tests.page
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/doc/virtual
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/compatibility.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/kramdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/latex.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/math_engine/itex2mml.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/math_engine/mathjax.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/math_engine/mathjaxnode.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/math_engine/ritex.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/pdf.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/remove_html_tags.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/syntax_highlighter.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/syntax_highlighter/coderay.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/syntax_highlighter/minted.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/syntax_highlighter/rouge.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/converter/toc.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/element.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/gfm.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/abbreviation.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/autolink.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/blank_line.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/block_boundary.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/blockquote.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/codeblock.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/codespan.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/emphasis.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/eob.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/escaped_chars.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/footnote.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/header.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/horizontal_rule.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/html_entity.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/line_break.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/link.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/list.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/math.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/paragraph.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/smart_quotes.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/kramdown/typographic_symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/parser/markdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/configurable.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/entities.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/string_scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/utils/unidecoder.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/lib/kramdown/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/man/man1/kramdown.1
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/run_tests.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/test_files.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/test_location.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/test_string_scanner_kramdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/01_blank_line/spaces.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/01_blank_line/spaces.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/01_blank_line/tabs.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/01_blank_line/tabs.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/beginning.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/beginning.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/middle.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/02_eob/middle.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/indented.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/indented.html.gfm
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/indented.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/no_newline_at_end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/no_newline_at_end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/one_para.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/one_para.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/two_para.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/03_paragraph/two_para.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/atx_header.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/atx_header.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/atx_header_no_newline_at_end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/atx_header_no_newline_at_end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/header_type_offset.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/header_type_offset.kramdown
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/header_type_offset.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/header_type_offset.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/header_type_offset.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/setext_header.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/setext_header.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/setext_header_no_newline_at_end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/setext_header_no_newline_at_end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_prefix.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_prefix.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_prefix.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_stripping.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_stripping.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_id_stripping.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_ids.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_ids.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/04_header/with_auto_ids.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/indented.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/indented.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/lazy.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/lazy.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/nested.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/nested.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/no_newline_at_end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/no_newline_at_end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/very_long_line.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/very_long_line.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/with_code_blocks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/05_blockquote/with_code_blocks.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/disable-highlighting.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/disable-highlighting.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/disable-highlighting.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/error.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/error.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted-with-opts.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted-with-opts.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted-with-opts.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-minted.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-opts.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-opts.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-opts.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-rouge.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-rouge.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting-rouge.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/highlighting.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/issue_gh45.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/issue_gh45.test
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/lazy.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/lazy.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/no_newline_at_end.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/no_newline_at_end.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/no_newline_at_end_1.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/no_newline_at_end_1.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/tilde_syntax.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/tilde_syntax.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/whitespace.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/whitespace.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_blank_line.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_blank_line.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_eob_marker.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_eob_marker.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block_name_with_dash.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block_name_with_dash.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/06_codeblock/with_lang_in_fenced_block_name_with_dash.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/error.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/error.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/error.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/sepspaces.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/sepspaces.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/septabs.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/07_horizontal_rule/septabs.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/escaping.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/escaping.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/item_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/item_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/lazy.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/lazy.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/list_and_hr.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/list_and_hr.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/list_and_others.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/list_and_others.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/mixed.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/mixed.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/nested.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/nested.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/other_first_element.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/other_first_element.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/simple_ol.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/simple_ol.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/simple_ul.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/simple_ul.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/single_item.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/single_item.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/special_cases.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/08_list/special_cases.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/comment.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/comment.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/deflists.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/deflists.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/deflists.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/tables.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/tables.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/content_model/tables.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html5_attributes.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html5_attributes.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_after_block.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_after_block.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_and_codeblocks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_and_codeblocks.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_and_codeblocks.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_and_headers.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_and_headers.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/code.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/code.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/comment.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/comment.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/emphasis.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/emphasis.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/entity.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/entity.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/header.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/header.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/header.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_dl.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_dl.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_ol.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_ol.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_ul.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/list_ul.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/paragraph.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/paragraph.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/table_normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/table_normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/table_simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/table_simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/typography.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/typography.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/html_to_native/typography.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/invalid_html_1.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/invalid_html_1.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/invalid_html_2.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/invalid_html_2.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/markdown_attr.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/markdown_attr.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/not_parsed.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/not_parsed.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_raw.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_raw.htmlinput
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_raw.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_raw.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_span.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_span.htmlinput
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_span.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_as_span.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_block_html.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_block_html.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/parse_block_html.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/processing_instruction.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/processing_instruction.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/simple.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/simple.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/textarea.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/09_html/textarea.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/10_ald/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/10_ald/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/auto_id_and_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/auto_id_and_ial.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/auto_id_and_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/nested.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/nested.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/11_ial/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/comment.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/comment.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/ignored.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/ignored.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/nomarkdown.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/nomarkdown.kramdown
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/nomarkdown.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/nomarkdown.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options2.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options2.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options3.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/12_extension/options3.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/definition_at_beginning.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/definition_at_beginning.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/deflist_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/deflist_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/item_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/item_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/multiple_terms.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/multiple_terms.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/no_def_list.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/no_def_list.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/para_wrapping.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/para_wrapping.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/separated_by_eob.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/separated_by_eob.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/styled_terms.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/styled_terms.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/too_much_space.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/too_much_space.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/with_blocks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/13_definition_list/with_blocks.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/errors.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/errors.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/escaping.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/escaping.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/footer.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/footer.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/header.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/header.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/no_table.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/no_table.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/simple.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/table_with_footnote.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/table_with_footnote.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/14_table/table_with_footnote.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/gh_128.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/gh_128.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/itex2mml.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/itex2mml.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/itex2mml.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview_simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview_simple.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjax_preview_simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_notexhints.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_notexhints.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_notexhints.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_semantics.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_semantics.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/mathjaxnode_semantics.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/ritex.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/ritex.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/15_math/ritex.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/no_toc.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/no_toc.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_exclude.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_exclude.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_exclude.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_levels.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_levels.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_levels.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_with_footnotes.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_with_footnotes.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/block/16_toc/toc_with_footnotes.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/encoding.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/encoding.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/empty.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/empty.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/empty_title.htmlinput
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/empty_title.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/image_in_a.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/image_in_a.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/imagelinks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/imagelinks.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/inline.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/inline.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/inline.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/link_defs.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/link_defs.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/link_defs_with_ial.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/link_defs_with_ial.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/links_with_angle_brackets.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/links_with_angle_brackets.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/reference.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/reference.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/reference.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/01_link/reference.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/empty.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/empty.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/errors.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/errors.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/nesting.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/nesting.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/02_emphasis/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/empty.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/empty.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/errors.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/errors.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-minted.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-minted.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-minted.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-rouge.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-rouge.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting-rouge.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/highlighting.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/03_codespan/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/definitions.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/definitions.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/definitions.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/footnote_nr.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/footnote_nr.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/footnote_nr.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/footnote_nr.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/inside_footnote.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/inside_footnote.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/markers.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/markers.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/markers.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/placement.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/04_footnote/placement.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/across_lines.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/across_lines.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/button.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/button.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/invalid.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/invalid.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/link_with_mailto.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/link_with_mailto.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/markdown_attr.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/markdown_attr.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/raw_span_elements.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/05_html/raw_span_elements.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/abbreviations/abbrev.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/abbreviations/abbrev.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/abbreviations/abbrev_defs.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/abbreviations/abbrev_defs.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/autolinks/url_links.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/autolinks/url_links.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/escaped_chars/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/escaped_chars/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/comment.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/comment.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/ignored.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/ignored.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/nomarkdown.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/nomarkdown.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/options.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/extension/options.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/ial/simple.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/ial/simple.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/line_breaks/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/line_breaks/normal.latex
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/line_breaks/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/itex2mml.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/itex2mml.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/itex2mml.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/mathjaxnode.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/mathjaxnode.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/mathjaxnode.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/normal.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/normal.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/ritex.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/ritex.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/math/ritex.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_char.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_char.html.19
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_char.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_char.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_input.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_input.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_as_input.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_numeric.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_numeric.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_numeric.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_symbolic.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_symbolic.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/entities_symbolic.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/greaterthan.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/greaterthan.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/lowerthan.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/lowerthan.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/typography.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/typography.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases/span/text_substitutions/typography.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/atx_header.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/atx_header.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/backticks_disable_highlighting.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/backticks_disable_highlighting.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/backticks_disable_highlighting.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/backticks_syntax.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/backticks_syntax.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/hard_line_breaks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/hard_line_breaks.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/hard_line_breaks_off.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/hard_line_breaks_off.options
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/hard_line_breaks_off.text
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/two_para_hard_line_breaks.html
/usr/lib64/ruby/gems/2.3.0/gems/kramdown-1.7.0/test/testcases_gfm/two_para_hard_line_breaks.text
/usr/lib64/ruby/gems/2.3.0/specifications/kramdown-1.7.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/kramdown
